repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: forbid-submodules
- repo: https://github.com/adrienverge/yamllint
  rev: v1.35.1
  hooks:
    - id: yamllint
      args: [--strict, -c=.yamllint]
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.11.0
  hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ['@commitlint/config-conventional']
#- repo: https://github.com/jnorwood/helm-docs
#  rev:  v1.12.0
#  hooks:
#    - id: helm-docs
