apiVersion: v2
name: cube-stack
description: Cube Stack is an Umbrella Chart that contains everything needed to run Cube in production.
type: application
version: 0.1.4
appVersion: "0.31.6"
keywords:
  - cubejs
maintainers:
  - name: Luc Vauvillier
    email: luc.vauvillier@gmail.com
  - name: Adnan Rahic
    email: adnan@cube.dev
  - email: emmanuel@pelo.tech
    name: Emmanuel Gomez
sources:
  - https://github.com/cube-js/cube.js
dependencies:
  - name: cubejs
    condition: global.cubejs.enabled
    repository: https://www.pelo.tech/charts/
    version: "0.1.2"
  - name: cubestore
    condition: global.cubestore.enabled
    repository: https://www.pelo.tech/charts/
    version: "0.1.1"
  - name: redis
    condition: global.redis.enabled
    repository: https://charts.bitnami.com/bitnami
    version: "17.1.*"
