{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "lrsql.fullname" . }}
  labels:
   {{- include "lrsql.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    {{ .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
 {{- end }}
