apiVersion: v1
kind: Service
metadata:
  name: {{ include "lrsql.fullname" . }}
  labels:
    {{- include "lrsql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.containerPorts.http }}
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: {{ .Values.service.targetPort.http }}
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.http)) }}
      nodePort: {{ .Values.service.nodePorts.http }}
      {{- end }}
    {{- end }}
    {{- if .Values.containerPorts.https }}
    - name: https
      port: {{ .Values.service.ports.https }}
      targetPort: {{ .Values.service.targetPort.https }}
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.https)) }}
      nodePort: {{ .Values.service.nodePorts.https }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "lrsql.selectorLabels" . | nindent 4 }}
