name: publish-charts
on:
  push:
    branches:
      - main
#    paths:
#      - charts/**
#      - '!**/*.md'
  workflow_dispatch:
jobs: # TODO: refactor plublish of charts
  publish-charts:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: add Helm bitnami repo
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Build dependencies Helm - backstage
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: helm dependency build charts/backstage

      - name: Chart | Push - backstage
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: backstage
          repository: pelotech/charts
          tag: 0.2.3
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.github_token }}

      - name: Build dependencies Helm - cubejs
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: helm dependency build charts/cubejs

      - name: Chart | Push - cubejs
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: cubejs
          repository: pelotech/charts
          tag: 0.2.0
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.github_token }}

      - name: Build dependencies Helm - cuebestore
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: helm dependency build charts/cubestore

      - name: Chart | Push - cubestore
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: cubestore
          repository: pelotech/charts
          tag: 0.2.0
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.github_token }}

      - name: Build dependencies Helm - cube-stack
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: helm dependency build charts/cube-stack

      - name: Chart | Push - cube-stack
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: cube-stack
          repository: pelotech/charts
          tag: 0.2.0
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.github_token }}

      - name: Build dependencies Helm - mutating-webhook
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: helm dependency build charts/mutating-webhook

      - name: Chart | Push - mutating-webhook
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: mutating-webhook
          repository: pelotech/charts
          tag: 0.1.1
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.github_token }}

      - name: Build dependencies Helm - nodejs
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: helm dependency build charts/nodejs

      - name: Chart | Push - nodejs
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: nodejs
          repository: pelotech/charts
          tag: 0.2.1
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.github_token }}

      - name: Build dependencies Helm - pachyderm
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: helm dependency build charts/pachyderm

      - name: Chart | Push - pachyderm
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: pachyderm
          repository: pelotech/charts
          tag: 0.2.1
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.github_token }}

      - name: Build dependencies Helm - lrsql
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: helm dependency build charts/lrsql

      - name: Chart | Push - lrsql
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: lrsql
          repository: pelotech/charts
          tag: 0.1.0
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.github_token }}
