name: pre-commit
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install pre-commit
        run: pip install pre-commit

      - name: add Helm bitnami repo
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: helm repo add bitnami oci://registry-1.docker.io/bitnamicharts

      - name: Build dependencies Helm - lrsql
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: helm dependency build charts/lrsql

      - name: pre-commit
        run: pre-commit run --all-files --show-diff-on-failure
